version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ./selenoid/config:/etc/selenoid
      - ./build:/output
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./build:/opt/selenoid/video
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./target
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  tests:
    build: .
    network_mode: bridge
    links:
      - selenoid
      - selenoid-ui